apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-init
  name: mongo-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-init
  template:
    metadata:
      labels:
        app: mongo-init
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: app
                operator: In
                values:
              - rocket-chat
      containers:
      - args: 
        - bash
        - -c
        - 'for i in `seq 1 30`; do mongo mongo/rocketchat --eval "rs.initiate({ _id:
          ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})" && s=$? &&
          break || s=$?; echo "Tried $i times. Waiting 5 secs..."; sleep 5; done;
          (exit $s)'
        image: mongo
        name: mongo-init

