apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-data
  labels:
    pv: mongo-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mongo/mongo-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - rocket-chat

