apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  selector:
    matchLabels:
      pv: "mongo-data"
