apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hubot
  labels:
    pv: hubot
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /rocketchat/hubot
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - rocket-chat

