apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hubot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  selector:
    matchLabels:
      pv: hubot      
