apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rocketchat
  labels:
    pv: rocketchat
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - rocket-chat
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /rocketchat/upload
