apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      pv: "rocketchat"
